[tool.poetry]
name = "tsw"
version = "0.2.1"
description = "A python library to interact with Tournament Software"
authors = [
  "Luis Rueda <userlerueda@gmail.com>"
]
license = "GPL-3.0-or-later"
include = ["CHANGELOG.md", "LICENSE"]
readme = "README.md"
repository = "https://github.com/userlerueda/utr"

[tool.poetry.dependencies]
python = "^3.9"
daiquiri = "^3.2.1"
requests = "^2.28.1"
pandas = "^1.4.4"
openpyxl = "^3.0.10"
tabulate = "^0.8.10"
click = "^8.1.3"
pydantic = "^1.10.2"
python-dateutil = "^2.8.2"
beautifulsoup4 = "^4.11.1"
lxml = "^4.9.1"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.8.0"
pytest = "^7.1.3"
ipython = "^8.5.0"
pytest-cov = "^3.0.0"

[tool.pytest.ini_options]
addopts = "-svv --cov-report term-missing --cov=tsw"
testpaths = ["tests"]

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.docker
    | \*.egg-info
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79
force_grid_wrap = 0
multi_line_output = 3
use_parentheses = true
include_trailing_comma = true
ensure_newline_before_comments = true

[tool.poetry.scripts]
tsw = "tsw.main:cli"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"